const fs = require('fs');

const unflatten = (data) => {
  if (Object(data) !== data || Array.isArray(data)) return data;
  const result = {};
  for (const i in data) {
    const keys = i.split('.');
    keys.reduce((r, e, j) => {
      return r[e] || (r[e] = isNaN(Number(keys[j + 1])) ? (keys.length - 1 === j ? data[i] : {}) : []);
    }, result);
  }
  return result;
}

const en = {
  "nav.home": "Home",
  "nav.about": "About",
  "nav.products": "Products",
  "nav.contact": "Contact",
  "cta.viewProducts": "View Products",
  "cta.contactUs": "Contact Us",
  "cta.whatsapp": "WhatsApp Inquiry",
  "cta.chatWhatsapp": "Chat on WhatsApp",
  "cta.enquire": "Enquire",
  "hero.badge": "Trusted Weighing Solutions · Tumkur, Karnataka",
  "hero.title1": "Precision Weighing,",
  "hero.title2": "Engineered for Trust",
  "hero.subtitle": "Complete Weighing Solution for Retail, Dairy & Industrial Segments. Durable build and unmatched accuracy for retail, industrial, dairy and commercial use.",
  "hero.f1": "High Accuracy",
  "hero.f2": "Advanced Tech",
  "hero.f3": "Built to Last",
  "about.kicker": "About us",
  "about.title1": "Built on",
  "about.title2": "accuracy",
  "about.title3": ", driven by trust.",
  "about.p1": "Siddarama Tech Solution is a Tumkur-based provider of premium weighing systems under the Jioo brand. We operate across Karnataka and serve customers all over India through our dealer network — supplying advanced scales for retail, dairy, industrial and commercial operations.",
  "about.p2": "Every product we ship is tested for precision, calibrated for real-world conditions, and backed by hands-on service from our team.",
  "stat.delivered": "Reliable Products Delivered",
  "stat.customers": "Happy Customers",
  "stat.accuracy": "Weighing Accuracy",
  "stat.support": "Customer Support",
  "prod.kicker": "Our Products",
  "prod.title": "A weighing system for every need",
  "prod.subtitle": "From compact counter scales to heavy-duty 4 load cell platforms — premium build, dependable accuracy.",
  "prod.capacity": "Capacity",
  "prod.accuracy": "Accuracy",
  "prod.tabletop.name": "Tabletop Scale",
  "prod.tabletop.desc": "Compact, accurate counter scale ideal for retail counters, jewellery and small parcels.",
  "prod.portable.name": "Portable Scale",
  "prod.portable.desc": "Take-anywhere precision for couriers, farmers and on-site weighing.",
  "prod.platform.name": "Platform Scale",
  "prod.platform.desc": "Workhorse platform scale built for warehouses, mandis and shop floors.",
  "prod.loadcell.name": "4 Load Cell Platform Scale",
  "prod.loadcell.desc": "Precision-engineered industrial scale for heavy loads, drums and pallets.",
  "why.kicker": "Why choose us",
  "why.title": "Engineered for performance. Delivered with care.",
  "why.f1.t": "High Accuracy & Reliability",
  "why.f1.d": "Calibrated precision you can trust on every weighing — verified before dispatch.",
  "why.f2.t": "Durable & Long-Lasting",
  "why.f2.d": "Heavy-duty builds engineered for retail, industrial and outdoor use.",
  "why.f3.t": "Advanced Technology",
  "why.f3.d": "Modern load cells, bright displays and smart connectivity options.",
  "why.f4.t": "Competitive Pricing",
  "why.f4.d": "Straightforward pricing with no surprises — premium quality, fair value.",
  "why.f5.t": "Customer-Centric Support",
  "why.f5.d": "Friendly service from a Karnataka-based team that picks up the phone.",
  "test.kicker": "Testimonials",
  "test.title": "Trusted by businesses across Karnataka",
  "cta.need.title": "Need a weighing solution?",
  "cta.need.sub": "Contact us instantly on WhatsApp — quick quotes, friendly advice.",
  "contact.kicker": "Contact",
  "contact.title": "Let's find the right scale for you",
  "contact.sub": "Tell us a bit about your requirement and we'll get back fast.",
  "contact.phone": "Phone",
  "contact.email": "Email",
  "contact.address": "Address",
  "contact.hours": "Business Hours",
  "contact.hoursVal": "Mon – Sat · 9:30 AM – 7:30 PM",
  "contact.form.name": "Your Name",
  "contact.form.namePh": "Full name",
  "contact.form.phone": "Phone",
  "contact.form.phonePh": "Mobile number",
  "contact.form.email": "Email",
  "contact.form.message": "Message",
  "contact.form.messagePh": "Tell us what you're looking for…",
  "contact.form.send": "Send Enquiry",
  "contact.form.sending": "Sending…",
  "contact.toast": "Opening WhatsApp to send your enquiry…",
  "footer.quick": "Quick Links",
  "footer.contact": "Contact",
  "footer.follow": "Follow",
  "footer.hours": "Business hours",
  "footer.hoursVal": "Mon – Sat · 9:30 AM – 7:30 PM",
  "footer.rights": "All rights reserved.",
  "footer.tagline": "Complete Weighing Solution for Retail, Dairy & Industrial Segments",
  "prod.material": "Top Plate",
  "prod.downloadCatalog": "Download Catalog",
  "aboutPage.kicker": "Our story",
  "aboutPage.title1": "Precision is a",
  "aboutPage.title2": "promise we keep",
  "aboutPage.sub": "From a small workshop in Tumkur to weighing partner for hundreds of businesses across Karnataka — built on trust, service and engineering excellence.",
  "prodPage.kicker": "Our range",
  "prodPage.title1": "Weighing systems for",
  "prodPage.title2": "every workflow",
  "prodPage.sub": "From counter-top retail scales to heavy-duty industrial platforms — pick the model that fits your operation.",
  "contactPage.kicker": "Contact us",
  "contactPage.title1": "We're here to",
  "contactPage.title2": "help",
  "contactPage.sub": "Reach out by phone, WhatsApp or email — we respond fast.",
  "lang.label": "Language"
};

const kn = {
  "nav.home": "ಮುಖಪುಟ",
  "nav.about": "ನಮ್ಮ ಬಗ್ಗೆ",
  "nav.products": "ಉತ್ಪನ್ನಗಳು",
  "nav.contact": "ಸಂಪರ್ಕಿಸಿ",
  "cta.viewProducts": "ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ",
  "cta.contactUs": "ಸಂಪರ್ಕಿಸಿ",
  "cta.whatsapp": "ವಾಟ್ಸಾಪ್ ವಿಚಾರಣೆ",
  "cta.chatWhatsapp": "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಚಾಟ್ ಮಾಡಿ",
  "cta.enquire": "ವಿಚಾರಿಸಿ",
  "hero.badge": "ವಿಶ್ವಾಸಾರ್ಹ ತೂಕ ಪರಿಹಾರಗಳು · ತುಮಕೂರು, ಕರ್ನಾಟಕ",
  "hero.title1": "ನಿಖರ ತೂಕ,",
  "hero.title2": "ವಿಶ್ವಾಸಕ್ಕಾಗಿ ರೂಪಿಸಲಾಗಿದೆ",
  "hero.subtitle": "ಚಿಲ್ಲರೆ ಮತ್ತು ಕೈಗಾರಿಕಾ ವಿಭಾಗಗಳಿಗೆ ಸಂಪೂರ್ಣ ತೂಕ ಪರಿಹಾರ. ಮುಂದುವರಿದ ತಂತ್ರಜ್ಞಾನ, ಬಾಳಿಕೆ ಬರುವ ರಚನೆ ಮತ್ತು ಅತ್ಯುತ್ತಮ ನಿಖರತೆ.",
  "hero.f1": "ಹೆಚ್ಚಿನ ನಿಖರತೆ",
  "hero.f2": "ಮುಂದುವರಿದ ತಂತ್ರಜ್ಞಾನ",
  "hero.f3": "ಬಾಳಿಕೆಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ",
  "about.kicker": "ನಮ್ಮ ಬಗ್ಗೆ",
  "about.title1": "ನಿರ್ಮಿತ",
  "about.title2": "ನಿಖರತೆ",
  "about.title3": " ಮೇಲೆ, ವಿಶ್ವಾಸದಿಂದ ಚಾಲಿತ.",
  "about.p1": "ಸಿದ್ದರಾಮ ಟೆಕ್ ಸೊಲ್ಯೂಷನ್ ತುಮಕೂರು ಮೂಲದ ಜಿಯೋ ಬ್ರಾಂಡ್ ಅಡಿಯಲ್ಲಿ ಪ್ರೀಮಿಯಂ ತೂಕ ವ್ಯವಸ್ಥೆಗಳ ಪೂರೈಕೆದಾರ. ನಿಖರತೆ, ಬಾಳಿಕೆ ಮತ್ತು ಮಾರಾಟದ ನಂತರದ ಸೇವೆಯ ಮೇಲೆ ಗಮನ ಕೇಂದ್ರೀಕರಿಸುತ್ತೇವೆ.",
  "about.p2": "ನಾವು ಕಳುಹಿಸುವ ಪ್ರತಿಯೊಂದು ಉತ್ಪನ್ನವನ್ನು ನಿಖರತೆಗಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ನಮ್ಮ ತಂಡದಿಂದ ಬೆಂಬಲಿಸಲಾಗುತ್ತದೆ.",
  "stat.delivered": "ವಿತರಿಸಿದ ಉತ್ಪನ್ನಗಳು",
  "stat.customers": "ಸಂತೋಷದ ಗ್ರಾಹಕರು",
  "stat.accuracy": "ತೂಕ ನಿಖರತೆ",
  "stat.support": "ಗ್ರಾಹಕ ಬೆಂಬಲ",
  "prod.kicker": "ನಮ್ಮ ಉತ್ಪನ್ನಗಳು",
  "prod.title": "ಪ್ರತಿ ಅಗತ್ಯಕ್ಕೆ ತೂಕ ವ್ಯವಸ್ಥೆ",
  "prod.subtitle": "ಕಾಂಪ್ಯಾಕ್ಟ್ ಕೌಂಟರ್ ಸ್ಕೇಲ್‌ಗಳಿಂದ ಭಾರೀ-ಡ್ಯೂಟಿ 4 ಲೋಡ್ ಸೆಲ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳವರೆಗೆ.",
  "prod.capacity": "ಸಾಮರ್ಥ್ಯ",
  "prod.accuracy": "ನಿಖರತೆ",
  "prod.tabletop.name": "ಟೇಬಲ್‌ಟಾಪ್ ಸ್ಕೇಲ್",
  "prod.tabletop.desc": "ಚಿಲ್ಲರೆ ಕೌಂಟರ್‌ಗಳು, ಆಭರಣ ಮತ್ತು ಸಣ್ಣ ಪಾರ್ಸೆಲ್‌ಗಳಿಗೆ ಸೂಕ್ತವಾದ ಕಾಂಪ್ಯಾಕ್ಟ್ ನಿಖರ ಸ್ಕೇಲ್.",
  "prod.portable.name": "ಪೋರ್ಟಬಲ್ ಸ್ಕೇಲ್",
  "prod.portable.desc": "ಕೊರಿಯರ್, ರೈತರು ಮತ್ತು ಸ್ಥಳೀಯ ತೂಕಕ್ಕೆ ಎಲ್ಲಿಗೂ ಒಯ್ಯಬಹುದಾದ ನಿಖರತೆ.",
  "prod.platform.name": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸ್ಕೇಲ್",
  "prod.platform.desc": "ಗೋದಾಮುಗಳು, ಮಂಡಿಗಳು ಮತ್ತು ಅಂಗಡಿಗಳಿಗೆ ನಿರ್ಮಿತ ಭಾರೀ-ಡ್ಯೂಟಿ ಸ್ಕೇಲ್.",
  "prod.loadcell.name": "4 ಲೋಡ್ ಸೆಲ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಸ್ಕೇಲ್",
  "prod.loadcell.desc": "ಭಾರೀ ಲೋಡ್, ಡ್ರಮ್ ಮತ್ತು ಪ್ಯಾಲೆಟ್‌ಗಳಿಗೆ ನಿಖರ ಕೈಗಾರಿಕಾ ಸ್ಕೇಲ್.",
  "why.kicker": "ನಮ್ಮನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು",
  "why.title": "ಕಾರ್ಯಕ್ಷಮತೆಗಾಗಿ ರೂಪಿಸಲಾಗಿದೆ. ಕಾಳಜಿಯಿಂದ ವಿತರಿಸಲಾಗಿದೆ.",
  "why.f1.t": "ಹೆಚ್ಚಿನ ನಿಖರತೆ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹತೆ",
  "why.f1.d": "ಪ್ರತಿ ತೂಕದಲ್ಲೂ ನೀವು ನಂಬಬಹುದಾದ ಕ್ಯಾಲಿಬ್ರೇಟ್ ನಿಖರತೆ.",
  "why.f2.t": "ಬಾಳಿಕೆ ಮತ್ತು ದೀರ್ಘಕಾಲಿಕ",
  "why.f2.d": "ಚಿಲ್ಲರೆ, ಕೈಗಾರಿಕಾ ಮತ್ತು ಹೊರಾಂಗಣ ಬಳಕೆಗೆ ಭಾರೀ-ಡ್ಯೂಟಿ ರಚನೆ.",
  "why.f3.t": "ಮುಂದುವರಿದ ತಂತ್ರಜ್ಞಾನ",
  "why.f3.d": "ಆಧುನಿಕ ಲೋಡ್ ಸೆಲ್‌ಗಳು, ಪ್ರಕಾಶಮಾನ ಪ್ರದರ್ಶನಗಳು ಮತ್ತು ಸ್ಮಾರ್ಟ್ ಸಂಪರ್ಕ ಆಯ್ಕೆಗಳು.",
  "why.f4.t": "ಸ್ಪರ್ಧಾತ್ಮಕ ಬೆಲೆ",
  "why.f4.d": "ಆಶ್ಚರ್ಯವಿಲ್ಲದ ಸರಳ ಬೆಲೆ — ಪ್ರೀಮಿಯಂ ಗುಣಮಟ್ಟ, ನ್ಯಾಯ ಮೌಲ್ಯ.",
  "why.f5.t": "ಗ್ರಾಹಕ ಕೇಂದ್ರಿತ ಬೆಂಬಲ",
  "why.f5.d": "ಕರ್ನಾಟಕ ಮೂಲದ ತಂಡದಿಂದ ಸೌಹಾರ್ದಯುತ ಸೇವೆ.",
  "test.kicker": "ಪ್ರಶಂಸಾಪತ್ರಗಳು",
  "test.title": "ಕರ್ನಾಟಕದಾದ್ಯಂತ ವ್ಯವಹಾರಗಳ ವಿಶ್ವಾಸ",
  "cta.need.title": "ತೂಕ ಪರಿಹಾರ ಬೇಕೇ?",
  "cta.need.sub": "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ತಕ್ಷಣ ಸಂಪರ್ಕಿಸಿ — ತ್ವರಿತ ಉಲ್ಲೇಖಗಳು, ಸ್ನೇಹಪರ ಸಲಹೆ.",
  "contact.kicker": "ಸಂಪರ್ಕ",
  "contact.title": "ನಿಮಗೆ ಸರಿಯಾದ ಸ್ಕೇಲ್ ಹುಡುಕೋಣ",
  "contact.sub": "ನಿಮ್ಮ ಅಗತ್ಯವನ್ನು ತಿಳಿಸಿ, ನಾವು ಶೀಘ್ರವಾಗಿ ಮರಳಿ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.",
  "contact.phone": "ಫೋನ್",
  "contact.email": "ಇಮೇಲ್",
  "contact.address": "ವಿಳಾಸ",
  "contact.hours": "ವ್ಯವಹಾರ ಸಮಯ",
  "contact.hoursVal": "ಸೋಮ – ಶನಿ · 9:30 ರಿಂದ 7:30",
  "contact.form.name": "ನಿಮ್ಮ ಹೆಸರು",
  "contact.form.namePh": "ಪೂರ್ಣ ಹೆಸರು",
  "contact.form.phone": "ಫೋನ್",
  "contact.form.phonePh": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  "contact.form.email": "ಇಮೇಲ್",
  "contact.form.message": "ಸಂದೇಶ",
  "contact.form.messagePh": "ನೀವು ಏನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ ಎಂದು ತಿಳಿಸಿ…",
  "contact.form.send": "ವಿಚಾರಣೆ ಕಳುಹಿಸಿ",
  "contact.form.sending": "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
  "contact.toast": "ನಿಮ್ಮ ವಿಚಾರಣೆಯನ್ನು ಕಳುಹಿಸಲು ವಾಟ್ಸಾಪ್ ತೆರೆಯಲಾಗುತ್ತಿದೆ…",
  "footer.quick": "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
  "footer.contact": "ಸಂಪರ್ಕ",
  "footer.follow": "ಫಾಲೋ ಮಾಡಿ",
  "footer.hours": "ವ್ಯವಹಾರ ಸಮಯ",
  "footer.hoursVal": "ಸೋಮ – ಶನಿ · 9:30 ರಿಂದ 7:30",
  "footer.rights": "ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
  "footer.tagline": "ಚಿಲ್ಲರೆ, ಡೈರಿ ಮತ್ತು ಕೈಗಾರಿಕಾ ವಿಭಾಗಗಳಿಗೆ ಸಂಪೂರ್ಣ ತೂಕ ಪರಿಹಾರ",
  "prod.material": "ಮೇಲಿನ ಫಲಕ",
  "prod.downloadCatalog": "ಕ್ಯಾಟಲಾಗ್ ಡೌನ್‌ಲೋಡ್",
  "aboutPage.kicker": "ನಮ್ಮ ಕಥೆ",
  "aboutPage.title1": "ನಿಖರತೆ ಎಂಬುದು",
  "aboutPage.title2": "ನಾವು ಪಾಲಿಸುವ ಭರವಸೆ",
  "aboutPage.sub": "ತುಮಕೂರಿನ ಸಣ್ಣ ಕಾರ್ಯಾಗಾರದಿಂದ ಕರ್ನಾಟಕದಾದ್ಯಂತ ನೂರಾರು ವ್ಯವಹಾರಗಳ ತೂಕ ಪಾಲುದಾರನವರೆಗೆ.",
  "prodPage.kicker": "ನಮ್ಮ ಶ್ರೇಣಿ",
  "prodPage.title1": "ತೂಕ ವ್ಯವಸ್ಥೆಗಳು",
  "prodPage.title2": "ಪ್ರತಿ ಕಾರ್ಯಪ್ರವಾಹಕ್ಕಾಗಿ",
  "prodPage.sub": "ಚಿಲ್ಲರೆ ಸ್ಕೇಲ್‌ಗಳಿಂದ ಭಾರೀ ಕೈಗಾರಿಕಾ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗಳವರೆಗೆ.",
  "contactPage.kicker": "ಸಂಪರ್ಕಿಸಿ",
  "contactPage.title1": "ನಾವು ನಿಮಗೆ",
  "contactPage.title2": "ಸಹಾಯ ಮಾಡಲು ಇಲ್ಲಿದ್ದೇವೆ",
  "contactPage.sub": "ಫೋನ್, ವಾಟ್ಸಾಪ್ ಅಥವಾ ಇಮೇಲ್‌ನಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ.",
  "lang.label": "ಭಾಷೆ"
};

fs.writeFileSync('src/i18n/messages/en.json', JSON.stringify(unflatten(en), null, 2));
fs.writeFileSync('src/i18n/messages/kn.json', JSON.stringify(unflatten(kn), null, 2));
console.log('JSON generated');
